### ISSUE TITLE
join() method need better error handler/message

### ISSUE THREAD

**Issue by changmason** [dreamerslab/node.flow#1]
node.flow should provide a better error handler or error message,
when a user accidentally calls flow.join() without making any parallel() task,
because sometimes the loop may not fire up any parallel() task indeed.

for example, the following code cause an error if tasks.length == 0.

tasks.forEach( function( task){
  flow.parallel( function ( ready ){
    // ...
    // ...
    ready();
  });
}):

flow.join();

**Comment by ben-lin** [comment]
fixed in commit b593f4d9b7bf3f7e3a64c5548bf55af19d665582
