### ISSUE TITLE
Break node.flow flow

### ISSUE THREAD

**Issue by bdkzero** [dreamerslab/node.flow#2]
Hello,
I would like to know if is there any way to break (force exit) from a series if a task fails.
For example:
var flow = new Flow();
flow.series(function() {
  // do something that fails, goto directly to end
  this.failed = true;
}).series(function() {
  // do other stuff
  next();
}).end(function() {

});

Thanks,
Bdkzero

**Comment by ben-lin** [comment]
Nice, I should have though of that. i'll add a way to break it. Thanks!

**Comment by bdkzero** [comment]
Thankyou!

**Comment by ben-lin** [comment]
Fixed in commit 0ab0ea35284f110bb7dca75ed8e24c44cca9717b

check it out :)
