### ISSUE TITLE
[Question] Arguments

### ISSUE THREAD

**Issue by HugoCornu** [dreamerslab/node.flow#3]
Hi,
I am having trouble with passing arguments to tasks.

The priority is arguments from last task > arguments for each task > default arguments

But how can I make "arguments from last task" empty ?
Its seems to be filled with the task callback.

Hugo

**Comment by ben-lin** [comment]
There is no priority. You can throw in as many arguments as you want but the last argument is always a `next` callback to call the next task.

**Comment by HugoCornu** [comment]
Thk for your comment !
I believe it doesnt completly answer my question.
Let me illustrate with an exemple and maybe you can point me to what I m doing wrong :

  for (var i=0;i<=pageMax;i++){ 
            flow.series(function(i,next) {
                dostuff
                setTimeout(next,config.timeUnit)
            },i)
            flow.series(function(next) {
                var subFlow = new Flow();
                AnArray.forEach(function(element) {
                    subFlow.series(function(callback) {
                        element.doElementStuff(callback)
                    })

I tried this and when I expected to have i=1, I got i = 
function (){
      self[ '_' + next_type ].apply( self, slice.call( arguments ));
    });

You see the argument "arguments for each task" i was replace by the "arguments from last task" next.
I don't get why

**Comment by ben-lin** [comment]
Arguments come from `next` callback. You did not pass any argument into it.

**Comment by HugoCornu** [comment]
Yes exactly, thats why I dont understand why the 'i' get replaced by a function.

**Comment by ben-lin** [comment]
It does not get replaced. You did not pass anything in. It should be something like this.

```
for( var i = 0; i <= pageMax; i++ ){

  flow.series( function ( i, next ){
    setTimeout( function (){
      next( i );
    }, config.timeUnit );
  }, i );
}
```

**Comment by HugoCornu** [comment]
Ok I'll try that !
Thank you.

**Comment by ben-lin** [comment]
No problem :)
